name: Update Beecrowd Badge

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    paths:
      - 'beecrowd-stats.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run badge generator
        run: python beecrowd-stats.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add beecrowd-badge.svg
          git commit -m "🔄 update Beecrowd badge" || echo "No changes to commit"
          git push
