name: Update Beecrowd Stats

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Optional: allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Beecrowd Stats Script
        run: python beecrowd_stats.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md badge_*.json beecrowd_stats.md || true
          git commit -m "🔄 Update Beecrowd stats and badges" || echo "No changes to commit"
          git push
